# Generated by Django 2.2.6 on 2019-10-19 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0002_auto_20191019_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condition',
            old_name='select_code_text3',
            new_name='code',
        ),
    ]
