# Generated by Django 2.2.6 on 2019-10-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0003_auto_20191019_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
