# Generated by Django 2.2.6 on 2019-10-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0005_auto_20191019_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='start_date',
            field=models.DateTimeField(null=True, verbose_name='start date'),
        ),
    ]
